# Generated by Django 5.2.3 on 2025-07-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={'ordering': ['id'], 'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
        migrations.AlterModelOptions(
            name='guia',
            options={'verbose_name': 'Guia', 'verbose_name_plural': 'Guias'},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['apellido'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='destino',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen principal'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_destinos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del destino'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='asistencia_viajero',
            field=models.TextField(verbose_name='Asistencia al viajero'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='destino',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guia', to='api.destino', verbose_name='Destino relacionado'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='documentacion',
            field=models.TextField(verbose_name='Documentacion requerida'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='equipaje_permitido',
            field=models.TextField(verbose_name='Equipaje permitido'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción de la imagen'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.destino', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
