# Generated by Django 5.2.3 on 2025-07-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_destino_options_alter_guia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del destino'),
        ),
    ]
