# Generated by Django 5.2.3 on 2025-07-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_destino_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un destino con ese nombre.'}, max_length=100, unique=True, verbose_name='Nombre del destino'),
        ),
    ]
