# Generated by Django 5.2.3 on 2025-07-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_destino_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='newsletter_suscripto',
            field=models.BooleanField(default=True),
        ),
    ]
